const colors = {
  light: {
    text: "#0D0D1A",
    tint: "#9D8FFF",
    background: "#F5F4FF",
    foreground: "#0D0D1A",
    card: "#FFFFFF",
    cardForeground: "#0D0D1A",
    primary: "#7C6FE0",
    primaryForeground: "#FFFFFF",
    secondary: "#EAE8FF",
    secondaryForeground: "#0D0D1A",
    muted: "#F0EFF9",
    mutedForeground: "#6B6B80",
    accent: "#00C48C",
    accentForeground: "#FFFFFF",
    destructive: "#FF4D6A",
    destructiveForeground: "#FFFFFF",
    border: "#E0DEFC",
    input: "#E0DEFC",
    surface: "#FFFFFF",
    surfaceForeground: "#0D0D1A",
    warning: "#FFB830",
    warningForeground: "#0D0D1A",
    info: "#7C6FE0",
    success: "#00C48C",
  },
  dark: {
    text: "#F0EEFF",
    tint: "#9D8FFF",
    background: "#0D0D1A",
    foreground: "#F0EEFF",
    card: "#161628",
    cardForeground: "#F0EEFF",
    primary: "#9D8FFF",
    primaryForeground: "#0D0D1A",
    secondary: "#1E1E36",
    secondaryForeground: "#F0EEFF",
    muted: "#1A1A30",
    mutedForeground: "#8888A8",
    accent: "#00E5A0",
    accentForeground: "#0D0D1A",
    destructive: "#FF4D6A",
    destructiveForeground: "#FFFFFF",
    border: "#252540",
    input: "#252540",
    surface: "#161628",
    surfaceForeground: "#F0EEFF",
    warning: "#FFB830",
    warningForeground: "#0D0D1A",
    info: "#9D8FFF",
    success: "#00E5A0",
  },
  radius: 16,
};

export default colors;
