import os

# Configuration
SOURCE_DIRS = ['app', 'components', 'constants', 'context', 'hooks', 'lib']
INCLUDE_FILES = ['app.json', 'package.json', 'tsconfig.json']
OUTPUT_FILE = 'SOURCE_CODE.md'
EXTENSIONS = ['.ts', '.tsx', '.js', '.jsx']

def generate_code_readme():
    print(f"Generating {OUTPUT_FILE}...")
    content = ["# FOCUS App Source Code\n\n", "This file is automatically generated and contains the core source code of the application.\n\n"]
    
    # Add standalone files first
    for filename in INCLUDE_FILES:
        if os.path.exists(filename):
            add_file_to_content(filename, content)
            
    # Walk through source directories
    for sdir in SOURCE_DIRS:
        if not os.path.exists(sdir):
            continue
            
        content.append(f"## Directory: `{sdir}`\n\n")
        for root, dirs, files in os.walk(sdir):
            # Sort files and dirs for consistency
            dirs.sort()
            files.sort()
            
            for file in files:
                if any(file.endswith(ext) for ext in EXTENSIONS):
                    filepath = os.path.join(root, file)
                    add_file_to_content(filepath, content)
                    
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.writelines(content)
        
    print(f"Successfully generated {OUTPUT_FILE} with {len(content)} entries.")

def add_file_to_content(filepath, content_list):
    rel_path = os.path.relpath(filepath)
    print(f"  Adding {rel_path}...")
    
    # Determine language for markdown block
    ext = os.path.splitext(filepath)[1]
    lang = 'typescript' if ext in ['.ts', '.tsx'] else 'javascript' if ext in ['.js', '.jsx'] else 'json'
    
    content_list.append(f"### File: `{rel_path}`\n\n")
    content_list.append(f"```{lang}\n")
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content_list.append(f.read())
    except Exception as e:
        content_list.append(f"// Error reading file: {e}")
    content_list.append("\n```\n\n")

if __name__ == "__main__":
    generate_code_readme()
